- name: Installation Domotic
  hosts: domotic 
  remote_user: pi 
  tasks:
    - name: Update et upgrade packets apt
      become: true
      apt:
        upgrade: yes
        update_cache: yes
    - name: Installation Git
      become: true
      apt: >
        name=git
        state=latest
    - name: Download zsh installer
      get_url: >
        url=https://deb.nodesource.com/setup_11.x
        dest=/tmp/setupNodeJs11.sh
        mode=777
    - name: Execute the setupNodeJs11.sh
      become: true
      shell: /tmp/setupNodeJs11.sh
    - name: Remove the setupNodeJs11.sh
      file: path=/tmp/setupNodeJs11.sh state=absent
    - name : Clone WiringPi
      git: >
        repo=git://git.drogon.net/wiringPi
        dest=~/wiringPi
    - name : Installation WiringPi
      command: cd ~/wiringPi && ./build