- name: Téléchargement setup Node.js
  get_url:
    url: https://deb.nodesource.com/setup_15.x
    dest: /tmp/setupNodeJs.sh
    mode: 777

- name: Exécution setup Node.js
  become: true
  shell: /tmp/setupNodeJs.sh

- name: Suppression setup Node.js
  file: path=/tmp/setupNodeJs.sh state=absent

- name: Installation Node.js
  become: true
  apt: 
    name: nodejs
    state: latest