- name: Téléchargement des sources
  git: 
    repo: git@github.com:sebsebseb1982/domotic2.git
    dest: ~/git/domotic2
    accept_hostkey: yes

- name: Copie configuration
  copy: 
    src: "{{ role_path }}/files/configuration.ts"
    dest: /home/pi/git/domotic2/src/configuration/configuration.ts

- name: Installation Avahi
  become: true
  apt:
    name: libavahi-compat-libdnssd-dev
    state: latest

- name: Installation des dépendances
  npm: 
    path: /home/pi/git/domotic2

- name: Lancement du script post-install
  shell: 
    cmd: npm run postinstall
    chdir: /home/pi/git/domotic2

- name: Mise à jour de @types/node
  npm:
    name: '@types/node'
    path: /home/pi/git/domotic2
    state: latest

- name: Installation globale de Typescript
  become: true
  npm:
    name: typescript
    global: yes

- name: Transpilation
  shell: 
    cmd: tsc
    chdir: /home/pi/git/domotic2